# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: reviung41
  - board: nice_nano_v2
    shield: contra
  - board: plonck
  - board: nice_nano_v2
    shield: istanbul_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: istanbul_right
  - board: nice_nano_v2
    shield: corne_tps65_left
  - board: nice_nano_v2
    shield: corne_tps65_right
  - board: nice_nano_v2
    shield: corne_tps43_left
  - board: nice_nano_v2
    shield: corne_tps43_right